"""fix

Revision ID: 3394cdfd1fb7
Revises: 48a1a8508b87
Create Date: 2026-05-07 17:57:13.549918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3394cdfd1fb7'
down_revision: Union[str, Sequence[str], None] = '48a1a8508b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.Enum('EMAIL', 'TELEGRAM', 'SMS', name='notificationtype'), nullable=False))
    op.add_column('notifications', sa.Column('channel_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('notifications', 'notification_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('notification_type', postgresql.ENUM('EMAIL', 'TELEGRAM', 'SMS', name='notificationtype'), autoincrement=False, nullable=False))
    op.drop_column('notifications', 'channel_data')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
